export type DataMode = "sample" | "import" | "real";
export type SalesSignal = "BEST_SELLER" | "RISING_SALES" | "STEADY" | "SLOW" | "STOCK_RISK" | "OVERSTOCK" | "INSUFFICIENT_DATA";
export type MarketMetricType = "RANKING" | "BEST_SELLER" | "POPULAR" | "NEW_ARRIVAL" | "COLLECTION_ORDER" | "CATALOG" | "UNKNOWN";
export type RankingScope = "SITEWIDE" | "DEPARTMENT" | "CATEGORY" | "SUBCATEGORY" | "UNKNOWN";
export type SignalConfidence = "BASELINE" | "EARLY_DATA" | "ACTIVE_SIGNAL";
export type MarketSignal = "HOT" | "RISING" | "FAST_RISING" | "NEW_ENTRY" | "STABLE" | "COOLING" | "DROPPING" | "BASELINE_COLLECTED" | "NEWLY_ADDED" | "STILL_PRESENT" | "REMOVED" | "INSUFFICIENT_DATA" | "NO_VERIFIED_RANKING";
export type ItemSignal = "HIGH_OPPORTUNITY" | "TREND_CONFIRMED" | "EARLY_SIGNAL" | "SATURATED" | "COOLING" | "STABLE" | "ASSORTMENT_RISING" | "CROSS_SOURCE_PRESENCE" | "NEW_ASSORTMENT_SIGNAL" | "INSUFFICIENT_DATA" | "NO_VERIFIED_RANKING";

export type SalesRow = {
  id: string;
  productCode: string;
  productName: string;
  brand: string | null;
  category: string | null;
  season: string | null;
  imageUrl: string | null;
  itemType: string | null;
  subItemType: string | null;
  salesQty: number | null;
  salesAmount: number | null;
  stockQty: number | null;
  sellThroughRate: number | null;
  normalSalesRate: number | null;
  discountRate: number | null;
  onlineSalesQty: number | null;
  storeSalesQty: number | null;
  change1w: number | null;
  change4w: number | null;
  signal: SalesSignal;
  dataMode: string;
};

export type MarketRow = {
  id: string;
  source: string;
  externalProductId: string;
  brand: string;
  name: string;
  category: string | null;
  url: string | null;
  imageUrl: string | null;
  itemType: string | null;
  subItemType: string | null;
  fit: string | null;
  mainColor: string | null;
  subColor: string | null;
  material: string | null;
  graphicType: string | null;
  detail: string | null;
  style: string | null;
  gender: string | null;
  metricType: MarketMetricType;
  rankingVerified: boolean;
  rankingScope: RankingScope;
  sourcePosition: number | null;
  rank: number | null;
  rankingCategory: string | null;
  observedCategory: string | null;
  audienceSegment: string | null;
  price: number | null;
  salePrice: number | null;
  discountRate: number | null;
  reviewCount: number | null;
  likeCount: number | null;
  change1w: number | null;
  change2w: number | null;
  change4w: number | null;
  change1d: number | null;
  change3d: number | null;
  change7d: number | null;
  consecutiveRise: number;
  consecutiveFall: number;
  firstSeen: Date | null;
  latestSeen: Date | null;
  peakRank: number | null;
  bestRank: number | null;
  averageRank: number | null;
  weeksInRanking: number;
  weeksInTop100: number;
  top20Weeks: number;
  rankVolatility: number | null;
  isNewEntry: boolean;
  presenceStatus: "BASELINE_COLLECTED" | "NEWLY_ADDED" | "STILL_PRESENT" | "REMOVED";
  signal: MarketSignal;
  dataMode: string;
  signalConfidence: SignalConfidence;
};

export type ItemTrendRow = {
  itemType: string;
  subItemType: string | null;
  label: string;
  category: string;
  isSpecific: boolean;
  marketStyleCount: number;
  marketTopCount: number;
  top10Presence: number;
  top20Presence: number;
  top50Presence: number;
  sourceCount: number;
  sources: string[];
  rankingSourceCount: number;
  assortmentSourceCount: number;
  currentCount: number;
  newlyAddedCount: number;
  removedCount: number;
  countChange1w: number | null;
  countChange4w: number | null;
  marketChange1w: number | null;
  marketChange2w: number | null;
  marketChange4w: number | null;
  averageRank: number | null;
  bestRank: number | null;
  avgMarketPrice: number | null;
  signalConfidence: SignalConfidence;
  rankingSignal: ItemSignal;
  assortmentSignal: ItemSignal;
  signal: ItemSignal;
};
